steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - asia.gcr.io/$PROJECT_ID/$_COMMAND:$_IMAGE_TAG
      - -f
      - ./docker/Dockerfile-$_COMMAND
      - .
substitutions:
  _IMAGE_TAG: latest
  _COMMAND: fetcher
images:
  - asia.gcr.io/$PROJECT_ID/$_COMMAND:$_IMAGE_TAG
