FROM golang:1.14-buster AS builder

RUN set -eux \
	&& apt-get install -y \
		bash \
		git \
		make

RUN echo "" > ~/.gitconfig \
    && git config --global url."https://github.com".insteadOf git://github.com \
    && git config --global http.https://gopkg.in.followRedirects true

WORKDIR /go/src/github.com/oinume/amamonitor
Add . /go/src/github.com/oinume/amamonitor
RUN make build/server


FROM alpine
COPY --from=builder /go/src/github.com/oinume/amamonitor/bin/server /server

RUN set -eux \
	&& apk --update add --no-cache ca-certificates

EXPOSE ${PORT:-5001}

ENTRYPOINT ["/server"]
